---
- name: Deploy Flask app with Docker
  hosts: web
  vars:
    docker_image: "{{ docker_image }}"
  tasks:
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Remove old container
      command: docker rm -f ansible-deneme
      ignore_errors: true

    - name: Pull latest image
      shell: docker pull {{ docker_image }}

    - name: Run new container
      command: docker run -d -p 80:5000 --name ansible-deneme {{ docker_image }}
